poi_list = [{
    "id": 1,
    "screen_name": "HHSGov",
    "country": "USA",
    "count": 500,
    "finished": 0,
    "reply_finished": 0
},
    {
        "id": 1,
        "screen_name": "CDCgov",
        "country": "USA",
        "count": 500,
        "finished": 0,
        "reply_finished": 0
    },
    {
        "id": 1,
        "screen_name": "JoeBiden",
        "country": "USA",
        "count": 500,
        "finished": 0,
        "reply_finished": 0
    },
    {
        "id": 1,
        "screen_name": "KamalaHarris",
        "country": "USA",
        "count": 500,
        "finished": 0,
        "reply_finished": 0
    },
    {
        "id": 1,
        "screen_name": "VP",
        "country": "USA",
        "count": 500,
        "finished": 0,
        "reply_finished": 0
    },
    {
        "id": 1,
        "screen_name": "POTUS45",
        "country": "USA",
        "count": 500,
        "finished": 0,
        "reply_finished": 0
    },
    {
        "id": 1,
        "screen_name": "POTUS",
        "country": "USA",
        "count": 500,
        "finished": 0,
        "reply_finished": 0
    },
    {
        "id": 1,
        "screen_name": "BarackObama",
        "country": "USA",
        "count": 500,
        "finished": 0,
        "reply_finished": 0
    },
    {
        "id": 1,
        "screen_name": "HillaryClinton",
        "country": "USA",
        "count": 500,
        "finished": 0,
        "reply_finished": 0
    },
    {
        "id": 1,
        "screen_name": "VP45",
        "country": "USA",
        "count": 500,
        "finished": 0,
        "reply_finished": 0
    },

    {
        "id": 1,
        "screen_name": "MoHFW_INDIA",
        "country": "INDIA",
        "count": 500,
        "finished": 0,
        "reply_finished": 0
    },
    {
        "id": 1,
        "screen_name": "narendramodi",
        "country": "INDIA",
        "count": 500,
        "finished": 0,
        "reply_finished": 0
    },
    {
        "id": 1,
        "screen_name": "PMOIndia",
        "country": "INDIA",
        "count": 500,
        "finished": 0,
        "reply_finished": 0
    },
    {
        "id": 1,
        "screen_name": "AmitShah",
        "country": "INDIA",
        "count": 500,
        "finished": 0,
        "reply_finished": 0
    },
    {
        "id": 1,
        "screen_name": "rajnathsingh",
        "country": "INDIA",
        "count": 500,
        "finished": 0,
        "reply_finished": 0
    },
    {
        "id": 1,
        "screen_name": "drharshvardhan",
        "country": "INDIA",
        "count": 500,
        "finished": 0,
        "reply_finished": 0
    },
    {
        "id": 1,
        "screen_name": "ShashiTharoor",
        "country": "INDIA",
        "count": 500,
        "finished": 0,
        "reply_finished": 0
    },
    {
        "id": 1,
        "screen_name": "RahulGandhi",
        "country": "INDIA",
        "count": 500,
        "finished": 0,
        "reply_finished": 0
    },
    {
        "id": 1,
        "screen_name": "MamataOfficial",
        "country": "INDIA",
        "count": 500,
        "finished": 0,
        "reply_finished": 0
    },
    {
        "id": 1,
        "screen_name": "ArvindKejriwal",
        "country": "INDIA",
        "count": 500,
        "finished": 0,
        "reply_finished": 0
    },

    {
        "id": 1,
        "screen_name": "SSalud_mx",
        "country": "MEXICO",
        "count": 500,
        "finished": 0,
        "reply_finished": 0
    },
    {
        "id": 1,
        "screen_name": "lopezobrador_",
        "country": "MEXICO",
        "count": 500,
        "finished": 0,
        "reply_finished": 0
    },
    {
        "id": 1,
        "screen_name": "EPN",
        "country": "MEXICO",
        "count": 500,
        "finished": 0,
        "reply_finished": 0
    },
    {
        "id": 1,
        "screen_name": "RicardoAnayaC",
        "country": "MEXICO",
        "count": 500,
        "finished": 0,
        "reply_finished": 0
    },
    {
        "id": 1,
        "screen_name": "marcelotorresc",
        "country": "MEXICO",
        "count": 500,
        "finished": 0,
        "reply_finished": 0
    },
    {
        "id": 1,
        "screen_name": "mario_delgado",
        "country": "MEXICO",
        "count": 500,
        "finished": 0,
        "reply_finished": 0
    }
]

covid_keywords = ['कोविड टीका',
                  'वैक्सीन',
                  'कोविड का टीका',
                  'कोवैक्सिन',
                  'कोविशिल्ड',
                  'वैक्सीनेशन',
                  'टीकाकरण',
                  'टीके',
                  'vaccine jab',
                  'वाइरस',
                  'dosis',
                  'teeka',
                  'sputnik v',
                  'doses',
                  'seconddose',
                  '#largestvaccinedrive',
                  'vaccinesamvaad',
                  'वैक्सीन जनादेश',
                  'एमआरएनए वैक्सीन',
                  'दूसरी खुराक',
                  'getvaxxed',
                  'ivermectin',
                  'vacunaton',
                  'vaccine hesitancy',
                  'injection',
                  'johnson',
                  'vaccine efficacy',
                  'रोग प्रतिरोधक शक्ति',
                  'segunda dosis',
                  'vacunado',
                  'खराब असर',
                  'pinchazo',
                  'yomevacunoseguro',
                  'vaccine dose',
                  'largestvaccinationdrive',
                  'estrategiadevacunación',
                  'vaccine mandate',
                  'side effects',
                  'novavax',
                  'vacunacion',
                  'vaccinepassport',
                  'पूर्ण टीकाकरण',
                  'vaccinessavelives',
                  'टीका_जीत_का',
                  'vacunarse',
                  'shots', 'vacuna',
                  'campaña de vacunación',
                  'कोवैक्सीन',
                  'फाइजर',
                  'कोविन',
                  'एस्ट्राजेनेका',
                  'टीका लगवाएं',
                  'टीकाकरण अभियान',
                  'sinopharm',
                  'sputnikv',
                  'mrna vaccine',
                  'vaccinationdrive',
                  'vaccinate',
                  'vacúnate',
                  'antibodies',
                  'efecto secundario',
                  'johnson & johnson',
                  'vaccineshortage',
                  'jab',
                  'anticuerpo',
                  'second dose',
                  'fullyvaccinated',
                  'covaxine',
                  'vaccinated',
                  'mrna',
                  'booster shots',
                  'unvaccinated',
                  'cansino',
                  'vacunación',
                  'cdc',
                  'वैक्सीन पासपोर्ट',
                  'covidshield',
                  'vaccinesamvad',
                  'immunity',
                  'inmunidad',
                  'पहली खुराक',
                  'लसीकरण',
                  'side effect',
                  'efficacy',
                  'clinical trial',
                  'vacunas',
                  'खुराक',
                  'vacunacovid19',
                  'tikautsav',
                  'vaccinequity',
                  'zycov-d',
                  'टीका',
                  'कोवेक्सिन',
                  'covidvaccine',
                  'vaccination drive',
                  'vaccination',
                  'fully vaccinated',
                  'vaccinemandate', 'covid vaccine',
                  'largestvaccinedrive',
                  'novaccinepassports',
                  'vacunada',
                  'getvaccinatednow',
                  'vaccine side effects',
                  'la inmunidad de grupo',
                  'efectos secundarios',
                  'remdesivir',
                  'get vaccinated',
                  'first dose',
                  'firstdose',
                  'dose',
                  'janssen',
                  'vaccinesideeffects',
                  'sinovac',
                  'एंटीबॉडी',
                  'वैक्सीन के साइड इफेक्ट',
                  'dosis de vacuna',
                  'booster',
                  'mandato de vacuna',
                  'vaccine',
                  'hydroxychloroquine',
                  'efectos secundarios de la vacuna',
                  'eficacia',
                  'प्रभाव',
                  'vacuna para el covid-19',
                  'j&j',
                  'cowin',
                  'astra zeneca',
                  'astrazenca',
                  'inyección de refuerzo',
                  'antibody',
                  'anticuerpos',
                  'herd immunity',
                  'eficacia de la vacuna',
                  'covid19vaccine',
                  'covid-19 vaccine',
                  'primera dosis',
                  'j&j vaccine',
                  'vacunar',
                  'vaccines',
                  'कोविशील्ड',
                  'inmunización',
                  'johnson and johnson',
                  'completamente vacunado',
                  'tikakaran',
                  'vaccine passports',
                  'johnson & johnson’s janssen', 'pfizer', 'sputnik', 'moderna', 'astrazeneca', 'covishield', 'covaxin',
                  'booster shot', 'vacuna covid',
                  'we4vaccine',
                  'vaccinepassports',
                  'vaccinehesitancy',
                  'vaccineswork',
                  'sabkovaccinemuftvaccine',
                  'covidvaccination',
                  'दुष्प्रभाव',
                  'pasaporte de vacuna',
                  'getvaccinated',
                  'vaccine passport',
                  'clinical trials']
